# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.3.4
      
     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.79.1'
           
      
      # Runs a single command using the runners shell
      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          external_repository: adityakeyal/adityakeyal.github.io
          personal_token: abcd
          publish_dir: ./public
          user_name: adityakeyal
          user_email: adi.keyal@gmail.com
          publish_branch: master
      